# vim:set ft=tmux:
%hidden MODULE_NAME="kubernetes"

set -gq "@catppuccin_${MODULE_NAME}_icon" "󰠳"
set -gqF "@catppuccin_${MODULE_NAME}_color" "#0080FF"
set -g "@catppuccin_status_${MODULE_NAME}_icon_bg" "#000000"
set -g "@catppuccin_status_${MODULE_NAME}_text_bg" "#000000"
set -g "@catppuccin_status_${MODULE_NAME}_icon_fg" "#0080FF"
set -g "@catppuccin_status_${MODULE_NAME}_text_fg" "#C0C0C0"
set -gq "@catppuccin_${MODULE_NAME}_text" "#($HOME/.sh/kubectl.tmux.sh)"

set -gF "@catppuccin_status_${MODULE_NAME}" \
  "#[fg=#0080FF,bg=#000000] #{@catppuccin_${MODULE_NAME}_icon}#[fg=#C0C0C0,bg=#000000] #{@catppuccin_${MODULE_NAME}_text}"
