# vim:set ft=tmux:
%hidden MODULE_NAME="podman"

set -gq "@catppuccin_${MODULE_NAME}_icon" "󰮄"
set -gqF "@catppuccin_${MODULE_NAME}_color" "#fab387"
set -g "@catppuccin_status_${MODULE_NAME}_icon_bg" "#000000"
set -g "@catppuccin_status_${MODULE_NAME}_text_bg" "#000000"
set -g "@catppuccin_status_${MODULE_NAME}_icon_fg" "#fab387"
set -g "@catppuccin_status_${MODULE_NAME}_text_fg" "#C0C0C0"
set -gq "@catppuccin_${MODULE_NAME}_text" "#($HOME/.sh/podman.tmux.sh)"

set -gF "@catppuccin_status_${MODULE_NAME}" \
  "#[fg=#fab387,bg=#000000] #{@catppuccin_${MODULE_NAME}_icon}#[fg=#C0C0C0,bg=#000000] #{@catppuccin_${MODULE_NAME}_text}"
