# vim:set ft=tmux:
# integrii theme — directory module
%hidden MODULE_NAME="directory"

set -ogq "@integrii_${MODULE_NAME}_icon" ""
set -ogqF "@integrii_${MODULE_NAME}_color" "#D75F00"
set -gq "@integrii_${MODULE_NAME}_text" "#{b:pane_current_path}"

set -gF "@integrii_status_${MODULE_NAME}" \
  "#[fg=#D75F00,bg=default] #{@integrii_${MODULE_NAME}_icon}#[fg=#C0C0C0,bg=default]#{@integrii_${MODULE_NAME}_text}"
