# vim:set ft=tmux:
# integrii theme — podman module
%hidden MODULE_NAME="podman"

set -gq "@integrii_${MODULE_NAME}_icon" "󰮄"
set -gqF "@integrii_${MODULE_NAME}_color" "#fab387"
set -gq "@integrii_${MODULE_NAME}_text" "#($HOME/.sh/podman.tmux.sh)"

set -gF "@integrii_status_${MODULE_NAME}" \
  "#[fg=#fab387,bg=default] #{@integrii_${MODULE_NAME}_icon}#[fg=#C0C0C0,bg=default] #{@integrii_${MODULE_NAME}_text}"
